fees:
  assessmentonly:
    low: £1,500
    high: £4,000
  iQTS:
    low: £7,950
    high: £9,950
  pgitt:
    domesticfulltime: £9,790
    domesticparttime: £7,335
    internationalaverage: £15,000
    internationalmaxfulltime: £36,000
    internationalmaxparttime: £17,500
  ugitt: £9,535
  pgittandugitt: £9,535
