finance:
# loans
  loanacademicyear: 2026 to 2027 academic year
  maintenanceloan:
    withparents: £9,118
    notwithparentsoutsidelondon: £10,830
    notwithparentsinsidelondon: £14,135
    oversixty: £4,582
  tuitionfeeloan:
    postgraduatemaxfulltime: £9,790
    postgraduatemaxparttime: £7,335
# parents and carers
  parentsacademicyear: 2025 to 2026 academic year
  parentslearningallowance:
    min: £50
    max: £2,024
    income: £18,957.98
  adultdependantsgrant:
    value: £3,545
    income: £15,835.98
  childcaregrantweeklypayment:
    one: £199.62
    twoplus: £342.24
# disability
  dsaacademicyear: 2025 to 2026 academic year
  disabilityadditionalfunding: £27,783
