finance:
  adultdependantsgrant:
    value: £3,438
    income: £15,621.98
  childcaregrantweeklypayment:
    one: £193.62
    twoplus: £331.95
  disabilityadditionalfunding: £26,948
  maintenanceloan:
    withparents: £8,877
    notwithparentsoutsidelondon: £10,544
    notwithparentsinsidelondon: £13,762
    oversixty: £4,461
    ## implemented above this line
  parentslearningallowance:
    min: £50
    max: £1,963
    income: £18,835.98
  tuitionfeeloan:
    postgraduatemaxfulltime: £9,535
    postgraduatemaxparttime: £7,145
