---
"training-bursary":
  title: "With a training bursary."
  description: |-
    Get personalised guidance to your inbox about becoming a teacher, including how to get a taste of teaching, advice from trainees and one-to-one support.
  subtitle: Could you teach it?
  image: "media/images/content/hero-images/m_dfe_lowther_room_6r_6595.jpg"
  noindex: true
