---
"overcoming-hurdles":
  title: "Free support when you apply to teach"
  description: |-
    Get personalised guidance to your inbox about becoming a teacher, including how to get a taste of teaching, advice from trainees and one-to-one support.
  image: "media/images/content/hero-images/m_dfe_lowther_room_6r_6595.jpg"
  title_bg_color: black-on-blue
  noindex: true
