---
acronyms:
  QTS: Qualified Teacher Status
  NQT: Newly Qualified Teacher
  DSA: Disabled Studentsâ€™ Allowance
  EU: European Union
  EEA: European Economic Area
  DfE: Department for Education
  TLR: Teaching and learning responsibility
  SCITT: School-Centred Initial Teacher Training
  CAS: Confirmation of Acceptance for Studies
  ICT: Information and Communication Technologies
  NPQ: National Professional Qualification
  SKE: subject knowledge enhancement
  PGDE: Postgraduate Diploma in Education
  PGCE: Postgraduate Certificate of Education
  BEd: Bachelor of Education degree
  BA: Bachelor of Arts
  BSc: Bachelor of Science
  ITT: Initial Teacher Training
  EYTS: Early Years Teacher Status
  EYITT: Early Years Initial Teacher Training
  SEND: Special Education Needs and Disabilities
  FE: Further Education
  AO: Assessment Only
  STEM: Science Technology Engineering Maths
  EY: Early Years
  TSA: Teaching School Alliance
  CPD: Continuing Professional Development
  TTA: Teacher Training Adviser
  TI: Teaching Internship
  NARIC: National Academic Recognition Information Centre
  ENIC: European Network of Information Centres
  SENCO: Special Educational Needs Coordinator
  GCSE: General Certificate of Secondary Education
