---
authentication: <%= ENV.fetch('SKYLIGHT_AUTH_TOKEN') %>
production:
  env: <%= ENV['SKYLIGHT_ENV'] %>
dev:
  env: <%= ENV['SKYLIGHT_ENV'] %>
test:
  env: <%= ENV['SKYLIGHT_ENV'] %>
preprod:
  env: <%= ENV['SKYLIGHT_ENV'] %>
rolling:
  env: <%= ENV['SKYLIGHT_ENV'] %>
userresearch:
  env: <%= ENV['SKYLIGHT_ENV'] %>
