name: Link Checker

on:
  schedule:
    - cron: "35 6 * * *"

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: Development
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0
        with:
          ref: master

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: DFE-Digital/github-actions/keyvault-yaml-secret@master
        id: SLACK-WEBHOOK
        with:
          keyvault: ${{ secrets.KEY_VAULT}}
          yaml_secret: INFRA-KEYS
          secret: SLACK-WEBHOOK

      - name: Check for broken links
        shell: pwsh
        run: |
              bundle exec rspec --format json --out result.json -t onschedule spec/features/external_links_spec.rb
              $results=$(Get-Content result.json | ConvertFrom-Json )
              $failures=$( $results.examples | where { $_.status -eq "failed" } )
              [regex]$regex = '(http[s]?|[s]?ftp[s]?)(:\/\/)([^\s,]+")
              $links=$( $regex.Matches($failures.exception.message).Value -replace '/"' , '' | get-unique )


      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_COLOR: ${{env.SLACK_ERROR}}
          SLACK_MESSAGE: Broken links found on Get into Teaching
          SLACK_TITLE: Broken links on GiT ${{ github.workflow }}
          SLACK_WEBHOOK: ${{ steps.SLACK-WEBHOOK.outputs.secret-value }}
