name: Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "35 6 * * *"

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: Development
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0
        with:
          ref: master

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: DFE-Digital/github-actions/keyvault-yaml-secret@master
        id: SLACK-WEBHOOK
        with:
          keyvault: ${{ secrets.KEY_VAULT}}
          yaml_secret: INFRA-KEYS
          secret: SLACK-WEBHOOK

      - name: List Broken Links
        run: |
              docker run -t --rm -e RAILS_ENV=test -v ${PWD}/out:/app/out  ${{ env.DOCKER_REPOSITORY }}:master  rspec --format json \
                            --out /app/out/result.json -t onschedule spec/features/external_links_spec.rb || true

      - name: Process broken links
        id:   links
        shell: pwsh
        run: |
              echo "::set-output name=urls::''"
              $results=$(Get-Content ${PWD}/out/result.json | ConvertFrom-Json )
              echo "Test results are:" $results.summary_line
              $failures=$( $results.examples | where { $_.status -eq "failed" } )
              echo "Failures are:" $failures.full_description
              [regex]$regex = '(http[s]?|[s]?ftp[s]?)(:\/\/)([^\s,]+")'
              $links=$( $regex.Matches($failures.exception.message).Value | get-unique ) -replace '"' 
              echo "Links are:" $links
              echo "::set-output name=urls::$links"

      - name: Slack Notification
        if: steps.links.outputs.urls != ''
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_COLOR: ${{env.SLACK_ERROR}}
          SLACK_MESSAGE: ${{ steps.links.outputs.urls }}
          SLACK_TITLE: Broken links on GiT ${{ github.workflow }}
          SLACK_WEBHOOK: ${{ steps.SLACK-WEBHOOK.outputs.secret-value }}
