name: Link Checker

on:
  schedule:
    - cron: "35 6 * * *"

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: Development
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.4
        with:
          ref: master

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: Azure/get-keyvault-secrets@v1.2
        id:   azSecret
        with:
           keyvault: ${{ secrets.KEY_VAULT}}
           secrets: 'SLACK-WEBHOOK'

      - name: Check for broken links
        run: |
          docker run -t --rm -e RAILS_ENV=test \
            ${{ env.DOCKER_REPOSITORY }}:master \
            rspec --format progress -t onschedule spec/features/external_links_spec.rb

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_COLOR: ${{env.SLACK_ERROR}}
          SLACK_MESSAGE: Broken links found on Get into Teaching
          SLACK_TITLE: Broken links on GiT ${{ github.workflow }}
          SLACK_WEBHOOK: ${{ steps.azSecret.outputs.SLACK-WEBHOOK }}
