name: Check users in space developer role

on:
  workflow_dispatch:
  schedule: # Midnight every day
    - cron: '0 0 * * *'

jobs:
  CHECK-SPACE-USER:
    runs-on: ubuntu-latest
    environment:
          Production
          
    steps:
      - uses: Azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: DfE-Digital/keyvault-yaml-secret@v1
        id:  keyvault-yaml-secret
        with:
          keyvault: ${{ secrets.KEY_VAULT}}
          secret: INFRA-KEYS
          key: PAAS-USERNAME, PAAS-PASSWORD, SLACK-WEBHOOK,  PAAS-USER-WHITELIST, PAAS-SPACE
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ steps.keyvault-yaml-secret.outputs.PAAS-USERNAME }}
          CF_PASSWORD: ${{ steps.keyvault-yaml-secret.outputs.PAAS-PASSWORD }}
          CF_SPACE_NAME: ${{ steps.keyvault-yaml-secret.outputs.PAAS-SPACE }}
          CF_ORG_NAME: dfe
          CF_API_URL:  https://api.london.cloud.service.gov.uk
          INSTALL_CONDUIT: false

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          repository: DFE-Digital/bat-infrastructure
          path: ./remote-checkout

      - name: Run powershell script
        shell: pwsh
        run: |
          ./remote-checkout/scripts/check-users-in-space-developer-role.ps1 `
            -Space "{{ steps.keyvault-yaml-secret.outputs.PAAS-SPACE }}" `
            -SlackWebhook "${{ steps.keyvault-yaml-secret.outputs.SLACK-WEBHOOK }}" `
            -Unset `
            -Whitelist "${{ steps.keyvault-yaml-secret.outputs.PAAS-USER-WHITELIST }}"
